### ISSUE TITLE
Constructor "headers" option is ignored when using Custom Client.

### ISSUE THREAD

**Issue by davloperez** [jmorganca/ollama-js#161]
The `headers` field of the Ollama constructor function options (AKA `Config` in interfaces.ts) is completely ignored in this constructor code, and thus, it is not taken into account when performing `fetch` from other methods. It probably should be stored in `this.config.headers`. 

This makes, for example, impossible to manually specify any Authorization custom header when performing our `/api/generate` loved requests :(

**Comment by davloperez** [comment]
Sorry, I didn't noticed that it has been fixed a couple days ago in https://github.com/ollama/ollama-js/pull/158

Waiting for the new version to have the fix.
Thanks!

**Comment by ParthSareen** [comment]
Just cut a new release! Should be available now 😄
